version = 1

test_patterns = ["*_test.go"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/lkeix/inspect-coverage-saas"

[[transformers]]
name = "gofumpt"
